---
name: Build container and push to Dockerhub
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push container to Dockerhub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: zerobaseio/smart-tracing
          tag_with_ref: true
          tag_with_sha: true
